# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'ppLedc' do

pod 'Alamofire'
pod 'Charts'
pod 'QRCodeReader.swift'
pod 'WechatOpenSDK'
pod 'CheckVersion_Swift'
end

